### ISSUE TITLE
GitLab CI pipeline running a script that uses the vale2cc.py tool fails if repo contains sym links

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/vale-at-red-hat#288]
A GitLab CI pipeline running a script that uses the vale2cc.py tool to generate a gl-code-quality-report.json report fails if the repository contains symlinks.

{
  "Code": "E100",
  "Text": "stat modules/modules: no such file or directory"
}
Traceback (most recent call last):
  File "vale2cc.py", line 16, in <module>
    vale_json = json.load(sys.stdin)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Screenshot of pipeline errors:**

![image](https://user-images.githubusercontent.com/92924207/188873240-aa79af51-66f3-4410-945d-972725fc6f46.png)

![image](https://user-images.githubusercontent.com/92924207/188874633-1c92693a-ec9f-4f7b-98e0-7a9ad0a2b58e.png)

Link to a merge request:
https://gitlab.cee.redhat.com/quarkus-documentation/qdocs-sandbox/-/merge_requests/20

When the repo contains zero sym links, the issue does not occur and the pipeline and code quality report works well.

**To Reproduce**

1. Enable Vale to run in a CI pipeline in GitLab as documented in [GitLab Code Quality reports](https://redhat-documentation.github.io/vale-at-red-hat/docs/user-guide/gitlab-code-quality-reports/) and docs on the vale-at-red-hat site
2. Use the configuration as per this sandbox repo:
https://gitlab.cee.redhat.com/quarkus-documentation/qdocs-sandbox/-/tree/main

**Note:** The script used here is:
```
script:
    - vale --no-exit --output=JSON . | python3 vale2cc.py > gl-code-quality-report.json

```
3. In a working branch, commit a folder that contains a symlink and then submit a merge request to **main**.

Results: The pipeline starts but fails on the errors above.

**Expected behavior**
The pipeline completes without error and the code quality report is visible from the MR.

**Additional context**
vale2cc.py does not handle symlinks. Is there a way we can get the utility to ignore them?

**Comment by aireilly** [comment]
Spent some time playing with this in the GL CI: code-quality demo is here: https://gitlab.cee.redhat.com/aireilly/asciidoc-vale-ci-demo

TL/DR as Michelle and I discovered; it's easier to just run vale against your PR changes and output to the log.
